"""Initial database schema with PostGIS

Revision ID: bcf9c05b9fb7
Revises:
Create Date: 2026-02-09 18:46:05.743568

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "bcf9c05b9fb7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column(
            "project_uuid",
            sa.UUID(),
            nullable=False,
            comment="Universal unique identifier for the project",
        ),
        sa.Column(
            "project_name", sa.String(), nullable=False, comment="Official project name"
        ),
        sa.Column(
            "project_type",
            sa.Enum(
                "HEALTH",
                "EDUCATION",
                "ROADS",
                "WATER",
                "MARKETS",
                "OTHER",
                name="projecttype",
            ),
            nullable=True,
            comment="Project category (health, education, roads, etc.)",
        ),
        sa.Column(
            "county",
            sa.String(length=50),
            nullable=True,
            comment="County where project is located",
        ),
        sa.Column(
            "constituency",
            sa.String(length=100),
            nullable=True,
            comment="Constituency within county",
        ),
        sa.Column(
            "ward",
            sa.String(length=100),
            nullable=True,
            comment="Ward within constituency",
        ),
        sa.Column(
            "estimated_value_kes",
            sa.DECIMAL(precision=15, scale=2),
            nullable=True,
            comment="Contract value in Kenya Shillings",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "AWARDED",
                "ONGOING",
                "COMPLETED",
                "ABANDONED",
                "STALLED",
                name="projectstatus",
            ),
            nullable=False,
            comment="Current project lifecycle status",
        ),
        sa.Column(
            "risk_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="risklevel"),
            nullable=True,
            comment="ML-predicted risk level",
        ),
        sa.Column(
            "risk_score",
            sa.Integer(),
            nullable=True,
            comment="Risk score from 0-100 (higher = more risky)",
        ),
        sa.Column(
            "confidence_score",
            sa.Integer(),
            nullable=True,
            comment="Data quality/completeness score 0-100",
        ),
        sa.Column(
            "geolocation_status",
            sa.String(length=50),
            nullable=False,
            comment="Status of geolocation: 'geolocated', 'not_geolocated', 'failed'",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("project_uuid"),
    )
    op.create_index(op.f("ix_projects_county"), "projects", ["county"], unique=False)
    op.create_index(
        op.f("ix_projects_project_name"), "projects", ["project_name"], unique=False
    )
    op.create_index(
        op.f("ix_projects_project_type"), "projects", ["project_type"], unique=False
    )
    op.create_index(
        op.f("ix_projects_risk_level"), "projects", ["risk_level"], unique=False
    )
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_table(
        "financial_records",
        sa.Column("financial_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project_uuid",
            sa.UUID(),
            nullable=False,
            comment="Reference to parent project",
        ),
        sa.Column(
            "source_system",
            sa.String(length=50),
            nullable=False,
            comment="Source: 'COB', 'Treasury', 'IFMIS', 'County'",
        ),
        sa.Column(
            "fiscal_year",
            sa.String(length=10),
            nullable=True,
            comment="Fiscal year e.g., '2023/2024'",
        ),
        sa.Column(
            "vote_head",
            sa.Integer(),
            nullable=True,
            comment="Government vote head number",
        ),
        sa.Column(
            "sub_vote",
            sa.Integer(),
            nullable=True,
            comment="Sub-vote number within vote head",
        ),
        sa.Column(
            "ministry",
            sa.String(),
            nullable=True,
            comment="Ministry or government entity",
        ),
        sa.Column(
            "department",
            sa.String(),
            nullable=True,
            comment="Department within ministry",
        ),
        sa.Column(
            "programme", sa.String(), nullable=True, comment="Budget programme name"
        ),
        sa.Column(
            "budget_allocated_kes",
            sa.DECIMAL(precision=15, scale=2),
            nullable=True,
            comment="Total budget allocated for project",
        ),
        sa.Column(
            "budget_released_kes",
            sa.DECIMAL(precision=15, scale=2),
            nullable=True,
            comment="Amount released from Treasury",
        ),
        sa.Column(
            "budget_absorbed_kes",
            sa.DECIMAL(precision=15, scale=2),
            nullable=True,
            comment="Amount actually spent/absorbed",
        ),
        sa.Column(
            "absorption_rate",
            sa.DECIMAL(precision=5, scale=2),
            nullable=True,
            comment="Absorption rate as percentage (0-100)",
        ),
        sa.Column(
            "reporting_period",
            sa.String(length=20),
            nullable=True,
            comment="Reporting period: 'Q1 2024', 'FY 2023/24'",
        ),
        sa.Column(
            "period_start_date",
            sa.Date(),
            nullable=True,
            comment="Start date of reporting period",
        ),
        sa.Column(
            "period_end_date",
            sa.Date(),
            nullable=True,
            comment="End date of reporting period",
        ),
        sa.Column(
            "document_source",
            sa.String(),
            nullable=True,
            comment="URL to source document (COB BIRR PDF)",
        ),
        sa.Column(
            "match_method",
            sa.String(length=50),
            nullable=True,
            comment="Matching method: 'direct', 'inference', 'manual'",
        ),
        sa.Column(
            "confidence_score",
            sa.Integer(),
            nullable=True,
            comment="Confidence in project-to-budget linking (0-100)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_uuid"], ["projects.project_uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("financial_id"),
    )
    op.create_index(
        op.f("ix_financial_records_fiscal_year"),
        "financial_records",
        ["fiscal_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_records_ministry"),
        "financial_records",
        ["ministry"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_records_project_uuid"),
        "financial_records",
        ["project_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_records_reporting_period"),
        "financial_records",
        ["reporting_period"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_records_vote_head"),
        "financial_records",
        ["vote_head"],
        unique=False,
    )
    op.create_table(
        "geolocation_records",
        sa.Column("geolocation_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project_uuid",
            sa.UUID(),
            nullable=False,
            comment="Reference to parent project",
        ),
        sa.Column(
            "source_system",
            sa.String(length=50),
            nullable=True,
            comment="Source: 'KMHFL', 'MOE', 'IEBC_Ward', 'Manual', 'OSM'",
        ),
        sa.Column(
            "facility_code",
            sa.String(length=50),
            nullable=True,
            comment="External facility code (e.g., KMHFL facility ID)",
        ),
        sa.Column(
            "facility_name",
            sa.String(),
            nullable=True,
            comment="Name of matched facility from registry",
        ),
        sa.Column(
            "latitude",
            sa.DECIMAL(precision=10, scale=7),
            nullable=False,
            comment="Latitude in decimal degrees (WGS84)",
        ),
        sa.Column(
            "longitude",
            sa.DECIMAL(precision=10, scale=7),
            nullable=False,
            comment="Longitude in decimal degrees (WGS84)",
        ),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
            comment="PostGIS Point geometry for spatial queries (SRID 4326 = WGS84)",
        ),
        sa.Column(
            "match_confidence",
            sa.Integer(),
            nullable=True,
            comment="Fuzzy match confidence score 0-100",
        ),
        sa.Column(
            "match_method",
            sa.String(length=50),
            nullable=True,
            comment="Method: 'exact', 'fuzzy', 'ward_fallback', 'manual', 'geocoding'",
        ),
        sa.Column(
            "match_score",
            sa.Integer(),
            nullable=True,
            comment="Algorithm-specific match score",
        ),
        sa.Column(
            "verified",
            sa.Boolean(),
            nullable=False,
            comment="Whether location has been manually verified",
        ),
        sa.Column(
            "verified_by",
            sa.String(length=100),
            nullable=True,
            comment="User who verified location",
        ),
        sa.Column(
            "verified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of verification",
        ),
        sa.Column(
            "address", sa.String(), nullable=True, comment="Text address if available"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_uuid"], ["projects.project_uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("geolocation_id"),
    )
    op.create_index(
        "idx_geolocation_records_geom",
        "geolocation_records",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_geolocation_records_project_uuid"),
        "geolocation_records",
        ["project_uuid"],
        unique=False,
    )
    op.create_table(
        "procurement_records",
        sa.Column("procurement_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project_uuid",
            sa.UUID(),
            nullable=False,
            comment="Reference to parent project",
        ),
        sa.Column(
            "source_system",
            sa.String(length=50),
            nullable=False,
            comment="Source system: 'PPIP', 'eGP', 'KeNHA', 'KURA', etc.",
        ),
        sa.Column(
            "tender_number",
            sa.String(),
            nullable=False,
            comment="Unique tender identifier from source system",
        ),
        sa.Column(
            "tender_title",
            sa.String(),
            nullable=True,
            comment="Official tender title/description",
        ),
        sa.Column(
            "procuring_entity",
            sa.String(),
            nullable=True,
            comment="Ministry/department/agency issuing tender",
        ),
        sa.Column(
            "contract_sum_kes",
            sa.DECIMAL(precision=15, scale=2),
            nullable=True,
            comment="Contract award amount in Kenya Shillings",
        ),
        sa.Column(
            "award_date", sa.Date(), nullable=True, comment="Date contract was awarded"
        ),
        sa.Column(
            "expected_completion_date",
            sa.Date(),
            nullable=True,
            comment="Expected project completion date",
        ),
        sa.Column(
            "contract_duration_months",
            sa.Integer(),
            nullable=True,
            comment="Contract duration in months",
        ),
        sa.Column(
            "contractor_name",
            sa.String(),
            nullable=True,
            comment="Name of awarded contractor/company",
        ),
        sa.Column(
            "contractor_pin",
            sa.String(length=20),
            nullable=True,
            comment="Contractor PIN (Personal Identification Number)",
        ),
        sa.Column(
            "contractor_nca_license",
            sa.String(length=50),
            nullable=True,
            comment="NCA (National Construction Authority) license number",
        ),
        sa.Column(
            "document_url",
            sa.String(),
            nullable=True,
            comment="URL to original tender document (PDF)",
        ),
        sa.Column(
            "document_s3_key",
            sa.String(),
            nullable=True,
            comment="S3 object key if document stored in cloud",
        ),
        sa.Column(
            "raw_ocr_text",
            sa.Text(),
            nullable=True,
            comment="Full extracted text from PDF for search",
        ),
        sa.Column(
            "data_quality",
            sa.Integer(),
            nullable=True,
            comment="OCR/extraction quality score 0-100",
        ),
        sa.Column(
            "extraction_method",
            sa.String(length=50),
            nullable=True,
            comment="Method used: 'api', 'scraping', 'ocr', 'manual'",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_uuid"], ["projects.project_uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("procurement_id"),
    )
    op.create_index(
        op.f("ix_procurement_records_award_date"),
        "procurement_records",
        ["award_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_records_contractor_name"),
        "procurement_records",
        ["contractor_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_records_procuring_entity"),
        "procurement_records",
        ["procuring_entity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_records_project_uuid"),
        "procurement_records",
        ["project_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_records_tender_number"),
        "procurement_records",
        ["tender_number"],
        unique=True,
    )
    op.create_table(
        "satellite_analyses",
        sa.Column("analysis_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project_uuid",
            sa.UUID(),
            nullable=False,
            comment="Reference to parent project",
        ),
        sa.Column(
            "sensor",
            sa.String(length=20),
            nullable=False,
            comment="Satellite sensor: 'Sentinel-1', 'Sentinel-2', 'SkySat'",
        ),
        sa.Column(
            "acquisition_date",
            sa.Date(),
            nullable=False,
            comment="Date satellite image was captured",
        ),
        sa.Column(
            "scene_id",
            sa.String(),
            nullable=True,
            comment="Original satellite scene identifier",
        ),
        sa.Column(
            "cloud_cover_percentage",
            sa.Integer(),
            nullable=True,
            comment="Cloud cover percentage (0-100) for optical imagery",
        ),
        sa.Column(
            "analysis_type",
            sa.String(length=50),
            nullable=False,
            comment="Analysis: 'NDVI_change', 'SAR_backscatter', 'RGB_inspection', 'NDWI_water'",
        ),
        sa.Column(
            "baseline_value",
            sa.DECIMAL(precision=10, scale=4),
            nullable=True,
            comment="Baseline metric value (pre-construction)",
        ),
        sa.Column(
            "current_value",
            sa.DECIMAL(precision=10, scale=4),
            nullable=True,
            comment="Current metric value",
        ),
        sa.Column(
            "change_magnitude",
            sa.DECIMAL(precision=10, scale=4),
            nullable=True,
            comment="Change in metric (current - baseline)",
        ),
        sa.Column(
            "change_detected",
            sa.Boolean(),
            nullable=False,
            comment="Whether significant change was detected",
        ),
        sa.Column(
            "ndvi_mean",
            sa.DECIMAL(precision=6, scale=4),
            nullable=True,
            comment="Mean NDVI value for project site",
        ),
        sa.Column(
            "ndvi_std",
            sa.DECIMAL(precision=6, scale=4),
            nullable=True,
            comment="Standard deviation of NDVI",
        ),
        sa.Column(
            "ndvi_min",
            sa.DECIMAL(precision=6, scale=4),
            nullable=True,
            comment="Minimum NDVI in area",
        ),
        sa.Column(
            "ndvi_max",
            sa.DECIMAL(precision=6, scale=4),
            nullable=True,
            comment="Maximum NDVI in area",
        ),
        sa.Column(
            "sar_vv_mean",
            sa.DECIMAL(precision=8, scale=4),
            nullable=True,
            comment="Mean VV backscatter (dB)",
        ),
        sa.Column(
            "sar_vh_mean",
            sa.DECIMAL(precision=8, scale=4),
            nullable=True,
            comment="Mean VH backscatter (dB)",
        ),
        sa.Column(
            "interpretation",
            sa.Text(),
            nullable=True,
            comment="Human-readable interpretation of analysis",
        ),
        sa.Column(
            "construction_phase",
            sa.String(length=50),
            nullable=True,
            comment="Detected phase: 'pre-construction', 'land_clearing', 'foundation', 'superstructure', 'completion'",
        ),
        sa.Column(
            "image_url",
            sa.String(),
            nullable=True,
            comment="URL to processed GeoTIFF in S3",
        ),
        sa.Column(
            "thumbnail_url",
            sa.String(),
            nullable=True,
            comment="URL to thumbnail/preview image",
        ),
        sa.Column(
            "tile_url_template",
            sa.String(),
            nullable=True,
            comment="XYZ tile URL template for web maps",
        ),
        sa.Column(
            "processing_algorithm",
            sa.String(length=50),
            nullable=True,
            comment="Algorithm used: 'satpy', 'pyrosar', 'snap'",
        ),
        sa.Column(
            "processing_date",
            sa.Date(),
            nullable=True,
            comment="Date analysis was performed",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_uuid"], ["projects.project_uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("analysis_id"),
    )
    op.create_index(
        op.f("ix_satellite_analyses_acquisition_date"),
        "satellite_analyses",
        ["acquisition_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_satellite_analyses_project_uuid"),
        "satellite_analyses",
        ["project_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_satellite_analyses_project_uuid"), table_name="satellite_analyses"
    )
    op.drop_index(
        op.f("ix_satellite_analyses_acquisition_date"), table_name="satellite_analyses"
    )
    op.drop_table("satellite_analyses")
    op.drop_index(
        op.f("ix_procurement_records_tender_number"), table_name="procurement_records"
    )
    op.drop_index(
        op.f("ix_procurement_records_project_uuid"), table_name="procurement_records"
    )
    op.drop_index(
        op.f("ix_procurement_records_procuring_entity"),
        table_name="procurement_records",
    )
    op.drop_index(
        op.f("ix_procurement_records_contractor_name"), table_name="procurement_records"
    )
    op.drop_index(
        op.f("ix_procurement_records_award_date"), table_name="procurement_records"
    )
    op.drop_table("procurement_records")
    op.drop_index(
        op.f("ix_geolocation_records_project_uuid"), table_name="geolocation_records"
    )
    op.drop_index(
        "idx_geolocation_records_geom",
        table_name="geolocation_records",
        postgresql_using="gist",
    )
    op.drop_table("geolocation_records")
    op.drop_index(
        op.f("ix_financial_records_vote_head"), table_name="financial_records"
    )
    op.drop_index(
        op.f("ix_financial_records_reporting_period"), table_name="financial_records"
    )
    op.drop_index(
        op.f("ix_financial_records_project_uuid"), table_name="financial_records"
    )
    op.drop_index(op.f("ix_financial_records_ministry"), table_name="financial_records")
    op.drop_index(
        op.f("ix_financial_records_fiscal_year"), table_name="financial_records"
    )
    op.drop_table("financial_records")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_risk_level"), table_name="projects")
    op.drop_index(op.f("ix_projects_project_type"), table_name="projects")
    op.drop_index(op.f("ix_projects_project_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_county"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
